Refactors build-sdks and copy-sdks

diff --git a/build-sdks b/build-sdks
--- a/build-sdks
+++ b/build-sdks
@@ -4,8 +4,47 @@ set -e
 
 DIR=$(cd `dirname $0` && pwd)
 SDKS=( dotnet java node php python ruby )
-BIN_DIR="${DIR}/bin"
+SHOW_HELP=0
 TARGET_SDK=
+
+while getopts ":t:h" opt; do
+  case $opt in
+    t) TARGET_SDK="$OPTARG"
+    ;;
+    h) SHOW_HELP=1
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
+function main() {
+  if [[ $SHOW_HELP -eq 1 ]]; then
+    show_help
+
+    exit 0
+  fi
+
+  if [[ -z ${TARGET_SDK} ]]; then
+    show_help
+
+    exit 0
+  fi
+
+  validate_sdk_choice $TARGET_SDK
+
+  if [[ "${TARGET_SDK}" != "all" ]]; then
+    build_sdk $TARGET_SDK
+  else
+    for SDK in "${SDKS[@]}"
+    do :
+      build_sdk $SDK
+    done
+  fi
+
+  printf "Success! All SDKs built!\n"
+  exit 0
+}
 
 function show_help() {
     cat << EOF
@@ -23,45 +62,39 @@ EOF
     exit 0
 }
 
-while getopts ":t:h" opt; do
-  case $opt in
-    t) TARGET_SDK="$OPTARG"
-    ;;
-    h) show_help
-    ;;
-    \?) echo "Invalid option -$OPTARG" >&2
-    ;;
-  esac
-done
-
-if [[ -z ${TARGET_SDK} ]]; then
-  show_help
-
-  exit 0
-fi
-
-if [[
-  "${TARGET_SDK}" != "all" &&
-  "${TARGET_SDK}" != "dotnet" &&
-  "${TARGET_SDK}" != "java" &&
-  "${TARGET_SDK}" != "node" &&
-  "${TARGET_SDK}" != "php" &&
-  "${TARGET_SDK}" != "python" &&
-  "${TARGET_SDK}" != "ruby"
-]]; then
-  printf "Invalid SDK (-t) value: ${TARGET_SDK}\n"
-  show_help
-
-  exit 1
-fi
-
-function build()
+function validate_sdk_choice()
 {
   SDK="$1"
 
+  if [[
+    "${SDK}" != "all" &&
+    "${SDK}" != "dotnet" &&
+    "${SDK}" != "java" &&
+    "${SDK}" != "node" &&
+    "${SDK}" != "php" &&
+    "${SDK}" != "python" &&
+    "${SDK}" != "ruby"
+  ]]; then
+    printf "Invalid SDK (-t) value: ${SDK}\n"
+    show_help
+
+    exit 1
+  fi
+}
+
+function build_sdk()
+{
+  SDK="$1"
+  SDK_DIR="${DIR}/sdks/${SDK}"
+
   printf "Building ${SDK} SDK\n"
 
-  bash "${BIN_DIR}/build-${SDK}"
+  clear_previous_build_files $SDK
+  copy_oas $SDK
+  copy_examples $SDK
+  copy_test_fixtures $SDK
+
+  bash "${SDK_DIR}/run-build"
 
   printf "\n\n"
   printf "########\n"
@@ -70,14 +103,80 @@ function build()
   printf "\n\n"
 }
 
-if [[ "${TARGET_SDK}" != "all" ]]; then
-  build $TARGET_SDK
-else
-  for SDK in "${SDKS[@]}"
-  do :
-    build $SDK
-  done
-fi
+function clear_previous_build_files()
+{
+  SDK="$1"
+  SDK_DIR="${DIR}/sdks/${SDK}"
 
-printf "Success! All SDKs built!\n"
-exit 0
+  printf "Clearing previous build files ...\n"
+
+  if [[ "${SDK}" == "dotnet" ]]; then
+    rm -rf "${SDK_DIR}/docs"
+    rm -rf "${SDK_DIR}/src/HelloSign"
+  elif [[ "${SDK}" == "java" ]]; then
+    rm -rf "${SDK_DIR}/docs"
+    rm -rf "${SDK_DIR}/src/main"
+  elif [[ "${SDK}" == "node" ]]; then
+    rm -rf "${SDK_DIR}/api"
+    rm -rf "${SDK_DIR}/dist"
+    rm -rf "${SDK_DIR}/docs"
+    rm -rf "${SDK_DIR}/model"
+    rm -rf "${SDK_DIR}/types"
+  elif [[ "${SDK}" == "php" ]]; then
+    rm -rf "${SDK_DIR}/docs"
+    rm -rf "${SDK_DIR}/src"
+  elif [[ "${SDK}" == "python" ]]; then
+    rm -rf "${SDK_DIR}/docs"
+    rm -rf "${SDK_DIR}/hellosign_sdk"
+  elif [[ "${SDK}" == "ruby" ]]; then
+    rm -rf "${SDK_DIR}/docs"
+    rm -rf "${SDK_DIR}/lib"
+  fi
+}
+
+function copy_oas()
+{
+  SDK="$1"
+  SDK_DIR="${DIR}/sdks/${SDK}"
+
+  printf "Copying openapi-sdk.yaml ...\n"
+  rm -f "${SDK_DIR}/openapi-sdk.yaml"
+  cp -r "${DIR}/openapi-sdk.yaml" "${SDK_DIR}/openapi-sdk.yaml"
+}
+
+function copy_examples()
+{
+  SDK="$1"
+  SDK_DIR="${DIR}/sdks/${SDK}"
+
+  printf "Copying examples ...\n"
+  rm -rf "${SDK_DIR}/examples"
+  mkdir -p "${SDK_DIR}/examples"
+
+  if [[ "${SDK}" == "dotnet" ]]; then
+    cp -r "${DIR}/examples/"*.cs "${SDK_DIR}/examples/"
+  elif [[ "${SDK}" == "java" ]]; then
+    cp -r "${DIR}/examples/"*.java "${SDK_DIR}/examples/"
+  elif [[ "${SDK}" == "node" ]]; then
+    cp -r "${DIR}/examples/"*.js "${SDK_DIR}/examples/"
+    cp -r "${DIR}/examples/"*.ts "${SDK_DIR}/examples/"
+  elif [[ "${SDK}" == "php" ]]; then
+    cp -r "${DIR}/examples/"*.php "${SDK_DIR}/examples/"
+  elif [[ "${SDK}" == "python" ]]; then
+    cp -r "${DIR}/examples/"*.py "${SDK_DIR}/examples/"
+  elif [[ "${SDK}" == "ruby" ]]; then
+    cp -r "${DIR}/examples/"*.rb "${SDK_DIR}/examples/"
+  fi
+}
+
+function copy_test_fixtures()
+{
+  SDK="$1"
+  SDK_DIR="${DIR}/sdks/${SDK}"
+
+  printf "Copying test_fixtures ...\n"
+  rm -rf "${SDK_DIR}/test_fixtures"
+  cp -r "${DIR}/test_fixtures" "${SDK_DIR}/test_fixtures"
+}
+
+main
diff --git a/copy-sdks b/copy-sdks
--- a/copy-sdks
+++ b/copy-sdks
@@ -4,9 +4,8 @@ set -e
 
 DIR=$(cd `dirname $0` && pwd)
 SDKS=( dotnet java node php python ruby )
-TARGET_DIR="${DIR}/repos"
+SHOW_HELP=0
 TARGET_SDK=
-BUILD_FIRST=0
 
 REPO_DOTNET="https://github.com/hellosign/hellosign-dotnet-sdk.git"
 REPO_JAVA="https://github.com/hellosign/hellosign-java-sdk.git"
@@ -14,6 +13,39 @@ REPO_NODE="https://github.com/hellosign/hellosign-nodejs-sdk.git"
 REPO_PHP="https://github.com/hellosign/hellosign-php-sdk.git"
 REPO_PYTHON="https://github.com/hellosign/hellosign-python-sdk.git"
 REPO_RUBY="https://github.com/hellosign/hellosign-ruby-sdk.git"
+
+while getopts ":t:h" opt; do
+  case $opt in
+    t) TARGET_SDK="$OPTARG"
+    ;;
+    h) SHOW_HELP=1
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
+function main() {
+  if [[ -z ${TARGET_SDK} ]]; then
+    show_help
+
+    exit 0
+  fi
+
+  validate_sdk_choice $TARGET_SDK
+
+  if [[ "${TARGET_SDK}" != "all" ]]; then
+    copy_files $TARGET_SDK
+  else
+    for SDK in "${SDKS[@]}"
+    do :
+      copy_files $SDK
+    done
+  fi
+
+  printf "Success! Ready for git commit!\n"
+  exit 0
+}
 
 function show_help() {
     cat << EOF
@@ -24,100 +56,73 @@ Copies build files for a given SDK into the repos/[SDK] directory.
             be DELETED, except for the .git directory!
 
 -t          target SDK, "all", "dotnet", "java", "node", "php", "python", "ruby"
--b          run the ./build-sdks script to first build all SDKs using openapi-generator.
-            defaults to 0 (no). Use 1 to build.
 -h          display this help and exit
-Example: copy-sdks -t php -b 1
+Example: copy-sdks -t php
 EOF
 
     exit 0
 }
 
-while getopts ":t:b:h" opt; do
-  case $opt in
-    t) TARGET_SDK="$OPTARG"
-    ;;
-    b) BUILD_FIRST="$OPTARG"
-    ;;
-    h) show_help
-    ;;
-    \?) echo "Invalid option -$OPTARG" >&2
-    ;;
-  esac
-done
-
-if [[ -z ${TARGET_SDK} ]]; then
-  show_help
-
-  exit 0
-fi
-
-if [[
-  "${TARGET_SDK}" != "all" &&
-  "${TARGET_SDK}" != "dotnet" &&
-  "${TARGET_SDK}" != "java" &&
-  "${TARGET_SDK}" != "node" &&
-  "${TARGET_SDK}" != "php" &&
-  "${TARGET_SDK}" != "python" &&
-  "${TARGET_SDK}" != "ruby"
-]]; then
-  printf "Invalid SDK (-t) value: ${TARGET_SDK}\n"
-  show_help
-
-  exit 1
-fi
-
-if [[ $BUILD_FIRST -eq 1 ]]; then
-  bash "${DIR}/build-sdks"
-  printf "\n\n"
-fi
-
-function get_repo()
+function validate_sdk_choice()
 {
   SDK="$1"
 
-  if [[ "${SDK}" == "dotnet" ]]; then
-    echo "${REPO_DOTNET}"
-  elif [[ "${SDK}" == "java" ]]; then
-    echo "${REPO_JAVA}"
-  elif [[ "${SDK}" == "node" ]]; then
-    echo "${REPO_NODE}"
-  elif [[ "${SDK}" == "php" ]]; then
-    echo "${REPO_PHP}"
-  elif [[ "${SDK}" == "python" ]]; then
-    echo "${REPO_PYTHON}"
-  elif [[ "${SDK}" == "ruby" ]]; then
-    echo "${REPO_RUBY}"
+  if [[
+    "${SDK}" != "all" &&
+    "${SDK}" != "dotnet" &&
+    "${SDK}" != "java" &&
+    "${SDK}" != "node" &&
+    "${SDK}" != "php" &&
+    "${SDK}" != "python" &&
+    "${SDK}" != "ruby"
+  ]]; then
+    printf "Invalid SDK (-t) value: ${SDK}\n"
+    show_help
+
+    exit 1
   fi
 }
 
 function copy_files()
 {
   SDK="$1"
+  SDK_DIR="${DIR}/repos/${SDK}"
 
-  if [[ ! -d "${TARGET_DIR}/${SDK}" ]] || [[ ! -d "${TARGET_DIR}/${SDK}/.git" ]]; then
-    REPO=$(get_repo "${SDK}")
-
-    printf "This script expects to find SDK repo cloned at ${TARGET_DIR}/${SDK}\n"
-    printf "Make sure to clone the SDK repo by using the following:\n\n"
-    printf "git clone --branch openapi ${REPO} ${TARGET_DIR}/${SDK}\n"
-
-    exit 1
+  if [[ ! -d "${SDK_DIR}" ]] || [[ ! -d "${SDK_DIR}/.git" ]]; then
+    repo_not_cloned $SDK
   fi
 
-  printf "Copying built files for the ${SDK} SDK to ${TARGET_DIR}/${SDK}\n"
-  rm -rf "${TARGET_DIR}/${SDK}/"*
-  cp -r "${DIR}/sdks/${SDK}/." "${TARGET_DIR}/${SDK}"
+  printf "Copying built files for the ${SDK} SDK to ${SDK_DIR}\n"
+  rm -rf "${SDK_DIR}/"*
+  cp -r "${DIR}/sdks/${SDK}/." "${SDK_DIR}"
 }
 
-if [[ "${TARGET_SDK}" != "all" ]]; then
-  copy_files $TARGET_SDK
-else
-  for SDK in "${SDKS[@]}"
-  do :
-    copy_files $SDK
-  done
-fi
+function repo_not_cloned()
+{
+  SDK="$1"
+  SDK_DIR="${DIR}/repos/${SDK}"
 
-printf "Success! Ready for git commit!\n"
-exit 0
+  if [[ "${SDK}" == "dotnet" ]]; then
+    REPO="${REPO_DOTNET}"
+  elif [[ "${SDK}" == "java" ]]; then
+    REPO="${REPO_JAVA}"
+  elif [[ "${SDK}" == "node" ]]; then
+    REPO="${REPO_NODE}"
+  elif [[ "${SDK}" == "php" ]]; then
+    REPO="${REPO_PHP}"
+  elif [[ "${SDK}" == "python" ]]; then
+    REPO="${REPO_PYTHON}"
+  elif [[ "${SDK}" == "ruby" ]]; then
+    REPO="${REPO_RUBY}"
+  fi
+
+  REPO=$(get_repo "${SDK}")
+
+  printf "This script expects to find SDK repo cloned at ${SDK_DIR}\n"
+  printf "Make sure to clone the SDK repo by using the following:\n\n"
+  printf "git clone --branch openapi ${REPO} ${SDK_DIR}\n"
+
+  exit 1
+}
+
+main
