Add a test for replacing defaultBasePath

diff --git a/sdks/node/bin/replace b/sdks/node/bin/replace
--- a/sdks/node/bin/replace
+++ b/sdks/node/bin/replace
@@ -35,5 +35,13 @@ rep 'TypeEnum_RequestSignature' \
 printf "\n\n"
 
 printf "Fixing broken defaultBasePath for OAuth endpoints ...\n"
-perl -pi -e 's#let defaultBasePath = "https://api.hellosign.com/v3";#let defaultBasePath = "https://app.hellosign.com";#g' "${ROOT_DIR}/api/oAuthApi.ts"
+perl -pi -e 's#let defaultBasePath = "https://api.hellosign.com/v3";#let defaultBasePath = "https://app.hellosign.com";#g' \
+  "${ROOT_DIR}/api/oAuthApi.ts"
+
+grep -ilr "https://api.hellosign.com/v3" "${ROOT_DIR}/api/oAuthApi.ts"
+if [ $? -eq 0 ]; then
+  printf "Error: https://api.hellosign.com/v3 server URL not replaced in api/oAuthApi.ts\n"
+  exit 1
+fi
+
 printf "\n\n"
